shell.run("delete", "stairs.lua")
shell.run("wget", "https://raw.githubusercontent.com/Coop25/TurtleTime/master/stairs.lua", "stairs.lua")
shell.run("delete", "utils.lua")
shell.run("wget", "https://raw.githubusercontent.com/Coop25/TurtleTime/master/utils/utils.lua", "utils.lua")
shell.run("delete", "startup.lua")
shell.run("wget", "https://raw.githubusercontent.com/Coop25/TurtleTime/master/startup.lua", "startup.lua")
shell.run("clear")
